package antivoland.game.asset;

class Animation {
    /* todo: rework
    public final List<Animation> animations = List.of(
            new Animation(300, // moon
                    NEW_MOON,
                    WAXING_CRESCENT_MOON,
                    FIRST_QUARTER_MOON,
                    WAXING_GIBBOUS_MOON,
                    FULL_MOON,
                    WANING_GIBBOUS_MOON,
                    LAST_QUARTER_MOON,
                    WANING_CRESCENT_MOON),
            new Animation(500, // globe
                    GLOBE_SHOWING_EUROPE_AFRICA,
                    GLOBE_SHOWING_AMERICAS,
                    GLOBE_SHOWING_ASIA_AUSTRALIA),
            new Animation(500, // camel
                    CAMEL,
                    TWO_HUMP_CAMEL),
            new Animation(500, // pig
                    PIG_FACE,
                    PIG_NOSE),
            new Animation(300,
                    ".",
                    "o",
                    "O",
                    "o",
                    "."
            ),
            new Animation(300,
                    "_",
                    "_",
                    "_",
                    "_",
                    "-",
                    "~",
                    "`",
                    "_"
            ),
            new Animation(250,
                    "░",
                    "▒",
                    "▓",
                    "▒",
                    "░"
            ),
            new Animation(400,
                    "’", "‛"),
            new Animation(400,
                    "†", "‡"),
            new Animation(400,
                    "∝", "∞"),
            new Animation(400,
                    "∴", "∻", "∵", "∻"),
            new Animation(400,
                    "∼", "∽"),
            new Animation(400,
                    "⊶", "⊷"),
            new Animation(400,
                    "⊹", " "),
            new Animation(400,
                    "⋋", "⋌"),
            new Animation(400,
                    "⋮", "⋰", "⋯", "⋱"),
            new Animation(400,
                    "⎜",
                    "⎡",
                    "⎛",
                    "⎡",
                    "⎜",
                    "⎤",
                    "⎞",
                    "⎤",
                    "⎜"),
            new Animation(400,
                    "⎟", "⎠", "⎟", "⎝"),
            new Animation(400,
                    "⊏", "⊂"),
            new Animation(200,
                    "←",
                    "←",
                    "↖",
                    "↑",
                    "↗",
                    "→",
                    "↘",
                    "↓",
                    "↙")
            //https://www.williamrobertson.net/documents/ascii.shtml
    );
     */
}